### ISSUE TITLE
Aplikasi ditutup namun masih ada di prosess, tidak berhenti.

### ISSUE THREAD

**Issue by rasyidf** [Kodesiana/KFlearning#2]
Ada bug dalam aplikasi ketika menutupnya. ia tidak benar benar hilang.

**Comment by fahminlb33** [comment]
Kayanya itu karena approach buat `ShowMetroDialogAsync` di `ProjectViewModel`.

https://github.com/Kodesiana/KFlearning/blob/6296904dcc622d99d2740d3d06a25e15d1c20f9a/src/KFlearning.IDE/ViewModels/ProjectViewModel.cs#L40

Pada 'CreateProjectViewModel', bagian ini:

https://github.com/Kodesiana/KFlearning/blob/6296904dcc622d99d2740d3d06a25e15d1c20f9a/src/KFlearning.IDE/ViewModels/CreateProjectViewModel.cs#L37-L48

Itu pakai `HideMetroDialogAsync`, mungkin karena itu ga di `Wait` jadi masih ada `Task` yang running. Tapi seharusnya ga masalah, karena behavior `Task` kan Background Thread yang seharusnya ikut mati saat app di close, tapi ini engga.

Ada saran? Mungkin ada cara yang "lebih tepat" untuk show dialog dengan MahApps, ini solusi yang engga sengaja soalnya :D
